### ISSUE TITLE
No support for non-frameworks?

### ISSUE THREAD

**Issue by master-nevi** [cocodelabs/NSAttributedString-CCLFormat#9]
![screen shot 2016-03-08 at 12 14 59 pm](https://cloud.githubusercontent.com/assets/987706/13614869/6b6b2d4e-e527-11e5-81e2-fe091a092108.png)

#### Any objections to doing it this way for max support?
![screen shot 2016-03-08 at 12 20 25 pm](https://cloud.githubusercontent.com/assets/987706/13615020/32cc2c62-e528-11e5-9c69-a39f83949e48.png)

```objective-c
#if __has_include("NSAttributedString+CCLFormat-umbrella.h")
@import Foundation;
#else
#import <Foundation/Foundation.h>
#endif
```

**Comment by jhoughjr** [comment]
This might fix the bull for me. thanks for pointing it out.

**Comment by kylef** [comment]
@master-nevi I'd happily accept a pull request to change the import for `#import <Foundation/Foundation.h>` directly. Unnecessarily to use `@import`, forgot about non-frameworks.

**Comment by master-nevi** [comment]
This somehow fixed itself when I used Xcode 7.3. Happily closing with no change needed.

**Comment by master-nevi** [comment]
Sorry the problem still exists. Xcode must have been caching the old compilation. I'll open a PR for this.

**Comment by master-nevi** [comment]
PR: https://github.com/cocodelabs/NSAttributedString-CCLFormat/pull/10

**Comment by master-nevi** [comment]
Awesome thanks!

**Comment by master-nevi** [comment]
@kylef If you have the time it would be great to have a release with this change.
